// CodeMind Academy — Phase 21: PostgreSQL cutover library.
//
// ONE parser, ONE DDL emitter, ONE table order, ONE value mapper shared by:
//   * scripts/db/make-postgres-schema.mjs      (derive schema.postgresql.prisma)
//   * scripts/db/postgres-baseline.sql         (generated by emitPostgresDdl; committed)
//   * scripts/db/migrate-sqlite-to-postgres.mjs (SQLite -> PostgreSQL copy)
//   * scripts/db/verify-postgres.mjs           (counts / constraints / coherence)
//   * scripts/verify-phase21-migration.mjs     (rehearsal against disposable PG)
//   * scripts/verify-phase21-restore.mjs       (restore drill against disposable PG)
//
// DESIGN (why a generator instead of hand-written SQL)
//   The Prisma engine binaries are unreachable from the build sandbox
//   (binaries.prisma.sh blocked — same limitation as Phases 6-20), so
//   `prisma migrate diff` cannot produce the PostgreSQL baseline here. The
//   baseline DDL is therefore DERIVED from `prisma/schema.prisma` by the
//   emitter below, committed as `scripts/db/postgres-baseline.sql`, and kept
//   honest by `tests/production-storage-phase21.test.js`, which regenerates
//   the DDL from the CURRENT schema on every run and fails on any drift.
//   There is exactly ONE schema source of truth (`prisma/schema.prisma`);
//   everything PostgreSQL is derived from it, never maintained in parallel.
//
// PORTABILITY CONTRACT (verified by the offline suite + the live drill)
//   * No Bytes / Json / Decimal / BigInt / autoincrement / @db.* /
//     dbgenerated() anywhere in the schema — every column maps to a core
//     PostgreSQL type (TEXT / INTEGER / DOUBLE PRECISION / BOOLEAN /
//     TIMESTAMPTZ(3) / native ENUM).
//   * String JSON blobs (Question.options, ExamAttempt.answers, …) stay TEXT
//     on PostgreSQL. There is deliberately NO JSONB conversion: the blobs are
//     opaque to the database (never filtered in SQL — grep  src/ for
//     queryRaw returns nothing), so converting them would buy nothing and
//     risk breaking byte-identity of the migration.
//   * Nullable UNIQUE columns (Student.nationalId, Batch(schoolType,courseId),
//     MockExamQuestion pairs, …) keep SQLite semantics on PostgreSQL: both
//     engines treat NULLs as distinct in UNIQUE constraints, so the migration
//     cannot introduce or drop duplicates.
//   * No raw SQL exists anywhere in src/ (all access is Prisma Client calls),
//     so the provider switch changes no application query.

import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const REPO = path.resolve(__dirname, "..", "..");
export const SCHEMA_PATH = path.join(REPO, "prisma", "schema.prisma");
export const PG_SCHEMA_PATH = path.join(REPO, "prisma", "schema.postgresql.prisma");
export const BASELINE_SQL_PATH = path.join(__dirname, "postgres-baseline.sql");

// Tables the engine owns. The ONLY table intentionally excluded from the
// SQLite -> PostgreSQL row copy: PostgreSQL gets its own migration ledger via
// `prisma migrate resolve --applied` (see docs/POSTGRES_CUTOVER_RUNBOOK.md).
// Everything else — including SecurityEvent, SecurityRateLimit, UserSession,
// PasswordResetToken, TeacherApplication, TeacherActivationToken — is copied
// 1:1. There is no "obsolete demo security data" carve-out: row history is
// never silently discarded (Phase 22 owns the production baseline cleanup).
export const MIGRATION_EXCLUDED_TABLES = new Set(["_prisma_migrations"]);

// ---------------------------------------------------------------------------
// 1. Schema parser (superset of scripts/lib/migrate-sqlite.mjs parsePrismaModels:
//    additionally captures @@index, relation targets, FK references and
//    ON DELETE actions, which the SQLite base-DDL derivation did not need).
// ---------------------------------------------------------------------------

/**
 * @returns {{ models: Map<string, {name:string, fields:Array, uniques:Array<Array<string>>, indexes:Array<Array<string>>}>,
 *             enums: Map<string, Array<string>>, order: Array<string> }}
 * field = { name, type, isList, optional, isRelation, isEnum, isId, unique,
 *           updatedAt, defaultRaw, relation: null | { name, fields, references, onDelete } }
 */
export function parseSchema(schemaPath = SCHEMA_PATH) {
  const text = fs.readFileSync(schemaPath, "utf8");
  const enums = new Map();
  for (const m of text.matchAll(/^enum\s+([A-Za-z0-9_]+)\s*\{([\s\S]*?)^\}/gm)) {
    const values = [];
    for (const line of m[2].split("\n")) {
      const t = line.trim();
      if (!t || t.startsWith("//")) continue;
      const v = /^([A-Za-z0-9_]+)/.exec(t);
      if (v) values.push(v[1]);
    }
    enums.set(m[1], values);
  }
  const blocks = [...text.matchAll(/^model\s+([A-Za-z0-9_]+)\s*\{([\s\S]*?)^\}/gm)];
  const modelNames = new Set(blocks.map((b) => b[1]));
  const models = new Map();
  const order = [];
  for (const [, name, body] of blocks) {
    order.push(name);
    const fields = [];
    const uniques = [];
    const indexes = [];
    for (const rawLine of body.split("\n")) {
      const line = rawLine.trim();
      if (!line || line.startsWith("//") || line.startsWith("///")) continue;
      if (line.startsWith("@@")) {
        const colsOf = (l) => {
          const inner = /\[([^\]]*)\]/.exec(l);
          return inner ? inner[1].split(",").map((c) => c.trim()).filter(Boolean) : [];
        };
        if (line.startsWith("@@unique(")) uniques.push(colsOf(line));
        else if (line.startsWith("@@index(")) indexes.push(colsOf(line));
        continue;
      }
      const m = /^(\w+)\s+([\w.]+)(\[\])?(\?)?\s*(.*)$/.exec(line);
      if (!m) continue;
      const [, fieldName, type, list, optional, rest] = m;
      const isList = !!list;
      const isRelation = modelNames.has(type) || /@relation/.test(rest);
      const isEnum = enums.has(type);
      const f = {
        name: fieldName,
        type,
        isList,
        optional: !!optional,
        isRelation,
        isEnum,
        isId: /@id\b/.test(rest),
        unique: /@unique\b/.test(rest),
        updatedAt: /@updatedAt\b/.test(rest),
        defaultRaw: null,
        relation: null,
      };
      const dflt = /@default\(((?:[^()]|\([^()]*\))*)\)/.exec(rest);
      if (dflt) f.defaultRaw = dflt[1].trim();
      const rel = /@relation\(([^)]*)\)/.exec(rest);
      if (rel) {
        const args = rel[1];
        const strName = /"([^"]+)"/.exec(args);
        const fieldsM = /fields:\s*\[([^\]]*)\]/.exec(args);
        const refsM = /references:\s*\[([^\]]*)\]/.exec(args);
        const delM = /onDelete:\s*([A-Za-z]+)/.exec(args);
        const updM = /onUpdate:\s*([A-Za-z]+)/.exec(args);
        f.relation = {
          name: strName ? strName[1] : null,
          fields: fieldsM ? fieldsM[1].split(",").map((x) => x.trim()).filter(Boolean) : null,
          references: refsM ? refsM[1].split(",").map((x) => x.trim()).filter(Boolean) : null,
          onDelete: delM ? delM[1] : null,
          onUpdate: updM ? updM[1] : null,
        };
      }
      fields.push(f);
    }
    models.set(name, { name, fields, uniques, indexes });
  }
  return { models, enums, order };
}

/** Scalar (physical) columns of a model, in declaration order. */
export function scalarFields(model) {
  return model.fields.filter((f) => !f.isRelation && !f.isList);
}

/** FK edges owned by a model: [{ fields, references, target, onDelete, onUpdate }]. */
export function fkEdges(model) {
  const out = [];
  for (const f of model.fields) {
    if (!f.isRelation || !f.relation || !f.relation.fields || !f.relation.fields.length) continue;
    out.push({
      field: f.name,
      target: f.type,
      fields: f.relation.fields,
      references: f.relation.references || [],
      onDelete: f.relation.onDelete,
      onUpdate: f.relation.onUpdate,
    });
  }
  return out;
}

// ---------------------------------------------------------------------------
// 2. PostgreSQL type + default mapping
// ---------------------------------------------------------------------------

const ON_DELETE_SQL = {
  Cascade: "CASCADE",
  SetNull: "SET NULL",
  Restrict: "RESTRICT",
  SetDefault: "SET DEFAULT",
  NoAction: "NO ACTION",
};

export function pgTypeOf(field) {
  if (field.isEnum) return `"${field.type}"`;
  switch (field.type) {
    case "String": return "TEXT";
    case "Int": return "INTEGER";
    case "BigInt": return "BIGINT";
    case "Float": return "DOUBLE PRECISION";
    case "Boolean": return "BOOLEAN";
    case "DateTime": return "TIMESTAMPTZ(3)";
    case "Bytes": return "BYTEA";
    case "Json": return "JSONB";
    case "Decimal": return "DECIMAL(65,30)";
    default:
      throw new Error(`pg-lib: no PostgreSQL mapping for Prisma type "${field.type}" (${field.name})`);
  }
}

function pgEscapeLiteral(s) {
  return s.replace(/'/g, "''");
}

/**
 * SQL DEFAULT for a scalar field, or null when the value is client-generated
 * (cuid(), @updatedAt) or absent. Throws on any default the cutover cannot
 * translate — an unknown default must fail the rehearsal, never be dropped.
 */
export function pgDefaultOf(field) {
  const d = field.defaultRaw;
  if (d === null || d === undefined) return null;
  if (d === "now()") return "CURRENT_TIMESTAMP";
  if (d === "cuid()" || d === "uuid()" || d === "autoincrement()") return null;
  if (d === "true") return "TRUE";
  if (d === "false") return "FALSE";
  if (/^-?\d+$/.test(d)) return d;
  if (/^-?\d+\.\d+$/.test(d)) return d;
  const str = /^"(.*)"$/s.exec(d);
  if (str) return `'${pgEscapeLiteral(str[1])}'`;
  if (/^[A-Za-z0-9_]+$/.test(d)) {
    // Bare token: an enum value (defaults are the only bare-token defaults in
    // this schema — verified by the offline suite).
    if (!field.isEnum) throw new Error(`pg-lib: bare default "${d}" on non-enum ${field.name}`);
    return `'${d}'`;
  }
  if (/^dbgenerated\(/.test(d)) throw new Error(`pg-lib: dbgenerated() default is provider-specific and forbidden in the portable schema (${field.name})`);
  throw new Error(`pg-lib: cannot translate default "${d}" (${field.name})`);
}

/** Prisma-style deterministic constraint/index names (63-byte PG limit). */
export function pgIdent(...parts) {
  const base = parts.join("_");
  if (Buffer.byteLength(base, "utf8") <= 63) return base;
  const hash = crypto.createHash("sha256").update(base).digest("hex").slice(0, 8);
  let cut = base.slice(0, 50);
  while (Buffer.byteLength(`${cut}_${hash}`, "utf8") > 63) cut = cut.slice(0, -1);
  return `${cut}_${hash}`;
}

// ---------------------------------------------------------------------------
// 3. Baseline DDL emitter
// ---------------------------------------------------------------------------

export function emitPostgresDdl(parsed = parseSchema()) {
  const { models, enums, order } = parsed;
  const lines = [];
  lines.push(`-- CodeMind Academy — Phase 21 PostgreSQL baseline DDL.`);
  lines.push(`-- GENERATED from prisma/schema.prisma by scripts/db/pg-lib.mjs — DO NOT EDIT.`);
  lines.push(`-- Regenerate: node scripts/db/make-postgres-schema.mjs --emit-ddl`);
  lines.push(`-- The offline suite (tests/production-storage-phase21.test.js) fails if this`);
  lines.push(`-- file drifts from what the emitter produces for the current schema.`);
  lines.push(`--`);
  lines.push(`-- Cutover use (engines available): prefer \`prisma db push\` on an empty`);
  lines.push(`-- database and baseline the migration history; use THIS file when the`);
  lines.push(`-- Prisma engines are unreachable or for byte-reviewable disaster recovery.`);
  lines.push(`-- See docs/POSTGRES_CUTOVER_RUNBOOK.md.`);
  lines.push(``);
  lines.push(`-- 1. Enums (native PostgreSQL enums; SQLite stores the same values as TEXT).`);
  for (const [name, values] of enums) {
    if (!values.length) throw new Error(`pg-lib: enum ${name} has no values`);
    lines.push(`CREATE TYPE "${name}" AS ENUM (${values.map((v) => `'${v}'`).join(", ")});`);
  }
  lines.push(``);
  lines.push(`-- 2. Tables, parents before children (migration order).`);
  const createOrder = migrationOrder(parsed);
  for (const table of createOrder) {
    const model = models.get(table);
    lines.push(...emitCreateTable(model));
    lines.push(``);
  }
  lines.push(`-- 3. Secondary indexes (@@index). Unique constraints are inline above.`);
  for (const table of createOrder) {
    const model = models.get(table);
    for (const cols of model.indexes) {
      const idx = pgIdent(table, ...cols, "idx");
      lines.push(`CREATE INDEX "${idx}" ON "${table}" (${cols.map((c) => `"${c}"`).join(", ")});`);
    }
  }
  lines.push(``);
  return lines.join("\n");
}

function emitCreateTable(model) {
  const cols = scalarFields(model);
  const defs = [];
  const ids = cols.filter((c) => c.isId);
  if (ids.length !== 1) throw new Error(`pg-lib: ${model.name} must have exactly one @id column (found ${ids.length})`);
  for (const c of cols) {
    let decl = `  "${c.name}" ${pgTypeOf(c)}`;
    if (!c.optional) decl += " NOT NULL";
    const dflt = pgDefaultOf(c);
    if (dflt !== null) decl += ` DEFAULT ${dflt}`;
    defs.push(decl);
  }
  defs.push(`  CONSTRAINT "${pgIdent(model.name, "pkey")}" PRIMARY KEY ("${ids[0].name}")`);
  for (const c of cols) {
    if (c.unique && !c.isId) {
      defs.push(`  CONSTRAINT "${pgIdent(model.name, c.name, "key")}" UNIQUE ("${c.name}")`);
    }
  }
  for (const u of model.uniques) {
    defs.push(`  CONSTRAINT "${pgIdent(model.name, ...u, "key")}" UNIQUE (${u.map((c) => `"${c}"`).join(", ")})`);
  }
  for (const fk of fkEdges(model)) {
    if (fk.fields.length !== fk.references.length || !fk.fields.length) {
      throw new Error(`pg-lib: ${model.name}.${fk.field} has unbalanced fields/references`);
    }
    const onDelete = fk.onDelete ? ON_DELETE_SQL[fk.onDelete] : null;
    if (fk.onDelete && !onDelete) throw new Error(`pg-lib: unknown onDelete ${fk.onDelete}`);
    // Prisma's PostgreSQL connector always emits ON UPDATE CASCADE; matching
    // it keeps `prisma migrate diff` clean after the cutover.
    const onUpdate = fk.onUpdate ? ON_DELETE_SQL[fk.onUpdate] : "CASCADE";
    if (fk.onUpdate && !ON_DELETE_SQL[fk.onUpdate]) throw new Error(`pg-lib: unknown onUpdate ${fk.onUpdate}`);
    let clause = `  CONSTRAINT "${pgIdent(model.name, ...fk.fields, "fkey")}" FOREIGN KEY (${fk.fields.map((c) => `"${c}"`).join(", ")}) REFERENCES "${fk.target}" (${fk.references.map((c) => `"${c}"`).join(", ")}) ON UPDATE ${onUpdate}`;
    if (onDelete) clause += ` ON DELETE ${onDelete}`;
    defs.push(clause);
  }
  return [`CREATE TABLE "${model.name}" (`, defs.join(",\n"), `);`];
}

// ---------------------------------------------------------------------------
// 4. Migration order (parents before children; deterministic; cycle = error)
// ---------------------------------------------------------------------------

export function migrationOrder(parsed = parseSchema()) {
  const { models, order } = parsed;
  // Edge parent -> child for every FK (self-loops excluded: a self-FK row can
  // still be inserted in one pass because the parent row sorts first only if
  // data cooperates — this schema has no self-FKs; assert that below).
  const childrenOf = new Map(); // parent -> Set(child)
  const indegree = new Map();
  for (const name of order) {
    childrenOf.set(name, new Set());
    indegree.set(name, 0);
  }
  for (const name of order) {
    for (const fk of fkEdges(models.get(name))) {
      if (!models.has(fk.target)) throw new Error(`pg-lib: ${name}.${fk.field} references unknown model ${fk.target}`);
      if (fk.target === name) throw new Error(`pg-lib: self-referencing FK ${name}.${fk.field} needs ordered-row handling`);
      if (!childrenOf.get(fk.target).has(name)) {
        childrenOf.get(fk.target).add(name);
        indegree.set(name, indegree.get(name) + 1);
      }
    }
  }
  // Kahn's algorithm with alphabetical tiebreak for determinism.
  const ready = [...order].filter((n) => indegree.get(n) === 0).sort();
  const out = [];
  while (ready.length) {
    const next = ready.shift();
    out.push(next);
    for (const child of [...childrenOf.get(next)].sort()) {
      indegree.set(child, indegree.get(child) - 1);
      if (indegree.get(child) === 0) {
        ready.push(child);
        ready.sort();
      }
    }
  }
  if (out.length !== order.length) {
    const stuck = order.filter((n) => !out.includes(n));
    throw new Error(`pg-lib: FK cycle detected involving: ${stuck.join(", ")}`);
  }
  return out;
}

// ---------------------------------------------------------------------------
// 5. Value mapping SQLite -> PostgreSQL driver values
// ---------------------------------------------------------------------------
// Prisma's SQLite connector stores Booleans as INTEGER 0/1 and DateTimes as
// TEXT (ISO-8601, UTC) or INTEGER milliseconds depending on the write path;
// the repo's own adapter (scripts/lib/sqlite-prisma-lite.mjs) accepts both.
// The mapper below is tolerant on READ (both shapes) and canonical on WRITE
// (native boolean / Date), so drivers (`pg`, PGlite) serialize correctly.

export function sqliteValueToPg(field, value) {
  if (value === null || value === undefined) return null;
  if (field?.type === "Boolean") {
    if (value === true || value === 1 || value === "1" || value === "t" || value === "true") return true;
    if (value === false || value === 0 || value === "0" || value === "f" || value === "false") return false;
    throw new Error(`pg-lib: unmappable Boolean ${JSON.stringify(value)} (${field.name})`);
  }
  if (field?.type === "DateTime") {
    if (value instanceof Date) {
      if (Number.isNaN(value.getTime())) throw new Error(`pg-lib: invalid Date (${field.name})`);
      return value;
    }
    if (typeof value === "number") {
      const d = new Date(Math.floor(value));
      if (Number.isNaN(d.getTime())) throw new Error(`pg-lib: invalid Date ms ${value} (${field.name})`);
      return d;
    }
    let s = String(value).trim();
    if (/^\d+$/.test(s)) {
      const d = new Date(Number(s));
      if (Number.isNaN(d.getTime())) throw new Error(`pg-lib: invalid Date ms ${s} (${field.name})`);
      return d;
    }
    // Prisma/SQLite naive form "YYYY-MM-DD HH:MM:SS.SSS" is UTC by connector
    // convention; ISO forms pass through untouched.
    if (/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}(\.\d+)?$/.test(s)) s = `${s.replace(" ", "T")}Z`;
    const d = new Date(s);
    if (Number.isNaN(d.getTime())) throw new Error(`pg-lib: invalid DateTime ${JSON.stringify(value)} (${field.name})`);
    return d;
  }
  if (field?.type === "Int" || field?.type === "BigInt") {
    const n = typeof value === "number" ? value : Number(value);
    if (!Number.isFinite(n)) throw new Error(`pg-lib: unmappable Int ${JSON.stringify(value)} (${field.name})`);
    return Math.floor(n);
  }
  if (field?.type === "Float") {
    const n = typeof value === "number" ? value : Number(value);
    if (!Number.isFinite(n)) throw new Error(`pg-lib: unmappable Float ${JSON.stringify(value)} (${field.name})`);
    return n;
  }
  return value;
}

/** Canonical JSON-able form for hashing/comparison (driver-independent). */
export function canonicalValue(field, value) {
  const v = sqliteValueToPg(field, value);
  if (v === null || v === undefined) return null;
  if (v instanceof Date) return v.toISOString();
  return v;
}

export function canonicalTableHash(rows, fields, pkCols) {
  const byName = new Map(fields.map((f) => [f.name, f]));
  const keyOf = (r) => pkCols.map((c) => JSON.stringify(canonicalValue(byName.get(c), r[c]) ?? null)).join("|");
  const sorted = [...rows].sort((a, b) => (keyOf(a) < keyOf(b) ? -1 : keyOf(a) > keyOf(b) ? 1 : 0));
  const h = crypto.createHash("sha256");
  for (const r of sorted) {
    const canon = {};
    for (const f of fields) canon[f.name] = canonicalValue(f, r[f.name] ?? null);
    h.update(JSON.stringify(canon));
    h.update("\n");
  }
  return h.digest("hex");
}

// ---------------------------------------------------------------------------
// 6. Copy: SQLite rows -> PostgreSQL (parameterized, batched, ID-preserving)
// ---------------------------------------------------------------------------

/**
 * @param {(text: string, params?: any[]) => Promise<{rows?: any[], rowCount?: number}>} pgQuery
 */
export async function copyTableToPg(pgQuery, model, rows, { batchSize = 500 } = {}) {
  const cols = scalarFields(model).map((f) => f.name);
  const byName = new Map(scalarFields(model).map((f) => [f.name, f]));
  if (!rows.length) return 0;
  let inserted = 0;
  for (let i = 0; i < rows.length; i += batchSize) {
    const batch = rows.slice(i, i + batchSize);
    const params = [];
    const tuples = batch.map((r) => {
      const ph = cols.map((c) => {
        params.push(sqliteValueToPg(byName.get(c), r[c] ?? null));
        return `$${params.length}`;
      });
      return `(${ph.join(", ")})`;
    });
    const sql = `INSERT INTO "${model.name}" (${cols.map((c) => `"${c}"`).join(", ")}) VALUES ${tuples.join(", ")}`;
    await pgQuery(sql, params);
    inserted += batch.length;
  }
  return inserted;
}

export async function pgRowCounts(pgQuery, tables) {
  const out = {};
  for (const t of tables) {
    const r = await pgQuery(`SELECT COUNT(*)::int AS n FROM "${t}"`);
    out[t] = r.rows[0].n;
  }
  return out;
}

// ---------------------------------------------------------------------------
// 7. SQL text helpers (dump / restore without pg_dump; deterministic)
// ---------------------------------------------------------------------------

/** Split on `;` respecting single-quoted literals, dollar quotes and comments. */
export function splitSqlStatements(sql) {
  const out = [];
  let cur = "";
  let i = 0;
  const n = sql.length;
  while (i < n) {
    const c = sql[i];
    const next2 = sql.slice(i, i + 2);
    if (next2 === "--") {
      while (i < n && sql[i] !== "\n") { cur += sql[i]; i++; }
      continue;
    }
    if (next2 === "/*") {
      cur += next2; i += 2;
      while (i < n && sql.slice(i, i + 2) !== "*/") { cur += sql[i]; i++; }
      cur += "*/"; i += 2;
      continue;
    }
    if (c === "'") {
      cur += c; i++;
      while (i < n) {
        cur += sql[i];
        if (sql[i] === "'") {
          if (sql[i + 1] === "'") { cur += sql[i + 1]; i += 2; continue; }
          i++;
          break;
        }
        i++;
      }
      continue;
    }
    if (c === "$") {
      const tag = /^\$[A-Za-z0-9_]*\$/.exec(sql.slice(i));
      if (tag) {
        const t = tag[0];
        cur += t; i += t.length;
        const end = sql.indexOf(t, i);
        if (end === -1) throw new Error("pg-lib: unterminated dollar quote");
        cur += sql.slice(i, end + t.length);
        i = end + t.length;
        continue;
      }
      cur += c; i++;
      continue;
    }
    if (c === ";") {
      if (cur.trim()) out.push(cur.trim());
      cur = "";
      i++;
      continue;
    }
    cur += c; i++;
  }
  if (cur.trim()) out.push(cur.trim());
  return out;
}

function pgLiteral(field, value) {
  const v = sqliteValueToPg(field, value);
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "boolean") return v ? "TRUE" : "FALSE";
  if (typeof v === "number") return Number.isInteger(v) ? String(v) : String(v);
  if (v instanceof Date) return `'${v.toISOString()}'`;
  return `'${pgEscapeLiteral(String(v))}'`;
}

/**
 * Deterministic logical dump of `tables` (parents first): header comment with
 * a JSON manifest (row counts + canonical sha256 per table), then one
 * multi-row INSERT per table. Restores with `restoreSqlDump` into any empty
 * baseline database.
 */
export async function dumpPostgresToSql(pgQuery, parsed, tables) {
  const { models } = parsed;
  const manifestTables = {};
  const chunks = [];
  for (const t of tables) {
    const model = models.get(t);
    const cols = scalarFields(model);
    const pk = cols.find((c) => c.isId)?.name || cols[0].name;
    const r = await pgQuery(`SELECT ${cols.map((c) => `"${c.name}"`).join(", ")} FROM "${t}" ORDER BY "${pk}"`);
    const rows = r.rows || [];
    manifestTables[t] = { count: rows.length, sha256: canonicalTableHash(rows, cols, [pk]) };
    if (!rows.length) continue;
    const tuples = rows.map((row) => `(${cols.map((c) => pgLiteral(c, row[c.name] ?? null)).join(", ")})`);
    chunks.push(`INSERT INTO "${t}" (${cols.map((c) => `"${c.name}"`).join(", ")}) VALUES\n${tuples.join(",\n")};`);
  }
  const manifest = {
    format: "codemind-pg-logical-dump/1",
    createdAt: new Date().toISOString(),
    tables: manifestTables,
  };
  const header = [
    `-- CodeMind Academy logical backup (Phase 21).`,
    `-- Restore into an EMPTY baseline database: see docs/POSTGRES_CUTOVER_RUNBOOK.md.`,
    `-- MANIFEST ${JSON.stringify(manifest)}`,
    ``,
  ].join("\n");
  const sql = header + (chunks.length ? chunks.join("\n\n") + "\n" : "");
  manifest.sha256 = crypto.createHash("sha256").update(sql).digest("hex");
  // Re-emit the header with the content hash bound (hash covers the manifest
  // line with sha256:null — the verifier recomputes the same way).
  const finalHeader = [
    `-- CodeMind Academy logical backup (Phase 21).`,
    `-- Restore into an EMPTY baseline database: see docs/POSTGRES_CUTOVER_RUNBOOK.md.`,
    `-- MANIFEST ${JSON.stringify({ ...manifest, sha256: null })}`,
    `-- SHA256 ${manifest.sha256}`,
    ``,
  ].join("\n");
  return { sql: finalHeader + (chunks.length ? chunks.join("\n\n") + "\n" : ""), manifest };
}

export function parseDumpManifest(sql) {
  const m = /^-- MANIFEST (\{.*\})$/m.exec(sql);
  if (!m) throw new Error("pg-lib: dump has no MANIFEST header");
  return JSON.parse(m[1]);
}

/** Execute a dump into the target in ONE transaction (all-or-nothing). */
export async function restoreSqlDump(query, sql) {
  const stmts = splitSqlStatements(sql);
  await query("BEGIN");
  try {
    for (const s of stmts) await query(s);
    await query("COMMIT");
  } catch (e) {
    try { await query("ROLLBACK"); } catch { /* already failed */ }
    throw e;
  }
  return stmts.length;
}

// ---------------------------------------------------------------------------
// 8. PostgreSQL backends (`pg` for production, PGlite for disposable drills)
// ---------------------------------------------------------------------------

export function pgBackend(poolOrClient) {
  return {
    kind: "pg",
    query: (text, params) => poolOrClient.query(text, params || []),
    close: async () => {
      if (typeof poolOrClient.end === "function") await poolOrClient.end();
    },
  };
}

export function pgliteBackend(pglite) {
  return {
    kind: "pglite",
    query: async (text, params) => {
      const r = await pglite.query(text, params || []);
      return { rows: r.rows || [], rowCount: r.rowCount ?? r.affectedRows ?? null };
    },
    close: async () => { await pglite.close(); },
  };
}

/** Redact credentials for logs/manifests (host + db only, never user/pass). */
export function redactDatabaseUrl(url) {
  try {
    const u = new URL(String(url));
    const host = u.host || "(local socket)";
    const db = u.pathname && u.pathname !== "/" ? u.pathname : "";
    return `${u.protocol}//${host}${db}`;
  } catch {
    return "(unparseable DATABASE_URL)";
  }
}
