// CodeMind Academy — Session materials / PDF delivery (Phase 14).
//
// THE CONTRACT
// ===========
// Session PDFs are stored ONCE as a `MediaAsset(DOCUMENT, LOCAL_PRIVATE)` and
// referenced by a `Material(ADMIN_UPLOADED)` row hanging off a Lesson. There is
// no second PDF table, no public filesystem path, and no new `pdfUrl` writes.
//
//   Lesson
//     └── Material(lessonId, kind=ADMIN_UPLOADED, trackScope, isActive, mediaAssetId)
//           └── MediaAsset(kind=DOCUMENT, storage=LOCAL_PRIVATE, storageKey, isPrivate)
//                 └── bytes under MEDIA_ROOT (never under /public)
//
// THE RULES THIS MODULE OWNS
// ==========================
//  1. Upload validation is `validatePdfUpload` in `src/lib/media.ts` — MIME,
//     extension, magic bytes (`%PDF-`), size cap. Callers MUST pass real bytes.
//  2. Storage keys are generated by `makeStorageKey` — never taken from the
//     client. Path traversal in a stored key is rejected by `resolveSafePath`.
//  3. Track isolation uses the SAME predicates as Phase 12
//     (`canAccessTrackScope` / `eligibleTrackScopes`). A LANGUAGE student never
//     downloads ARABIC material; SHARED is available to both. The decision is
//     derived from the student's own `schoolType` row (or a parent's linked
//     children's tracks) — never from UI locale, never from a request param.
//  4. Authorization for download reuses `canAccessLesson` (enrollment + course
//     + track + lifecycle + progression). Parent access reuses
//     `isParentLessonPreviewAllowed` (child course + child track + PUBLISHED +
//     not archived). There is no second progression engine here.
//  5. Uniqueness of "one active PDF per lesson × trackScope" is enforced by
//     deactivating prior active rows of the same scope on replace, not by a
//     partial unique index (deactivated history must survive for refcounting).
//  6. MediaAsset bytes are deleted ONLY when no Material (and no SessionVideo /
//     QuizAttemptEvidence) still references them. Reference counting is the
//     same pattern session-video DELETE already uses.
//  7. Student/parent payloads expose SAFE DESCRIPTORS only
//     (`id`, `title`, `kind`, `trackScope`, `downloadUrl`, `mimeType`,
//     `sizeBytes`). Never `storageKey`, never a filesystem path, never a
//     private URL. Locked/unpublished/wrong-track lessons do not reveal
//     material ids.
//  8. Legacy `Lesson.pdfUrl` is READ-ONLY compatibility. New uploads never
//     write it. Existing non-placeholder values may still be surfaced as a
//     legacy descriptor so older content keeps working until sunset.
//
// See docs/PHASE_14_PDF_SESSION_MATERIALS.md for the full contract.

import { db } from "@/lib/db";
import {
  deletePrivateFile,
  makeStorageKey,
  writePrivateFile,
  validatePdfUpload,
  MAX_PDF_BYTES,
  type PdfValidationResult,
} from "@/lib/media";
import {
  canAccessLesson,
  type AccessReason,
} from "@/lib/session-progress";
import {
  isStudentVisibleStatus,
} from "@/lib/session-lifecycle";
import {
  canAccessTrackScope,
  normalizeTrackScope,
  type TrackScope,
  TRACK_SCOPES,
} from "@/lib/track-scope";
import {
  isParentLessonPreviewAllowed,
  getParentTrackScopes,
} from "@/lib/parent-access";
import { getStudentSchoolType } from "@/lib/enrollment";
import { normalizeSchoolType, type SchoolType } from "@/lib/school-type";

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/** Safe descriptor returned to students/parents/admins. No storage keys. */
export type MaterialDescriptor = {
  id: string;
  title: string;
  kind: "ADMIN_UPLOADED" | "GENERATED" | "LEGACY_URL";
  trackScope: TrackScope;
  /** Authorized download path — NEVER a filesystem path or private URL. */
  downloadUrl: string | null;
  mimeType: string | null;
  sizeBytes: number | null;
  /** true when this is a legacy `Lesson.pdfUrl` compatibility descriptor. */
  legacy: boolean;
};

export type MaterialUploadInput = {
  lessonId: string;
  buffer: Buffer | Uint8Array;
  claimedMime?: string | null;
  originalName?: string | null;
  title?: string | null;
  /** Defaults to the lesson's own trackScope when omitted. */
  trackScope?: unknown;
  actorUserId?: string | null;
  maxBytes?: number;
};

export type MaterialUploadResult =
  | {
      ok: true;
      material: {
        id: string;
        lessonId: string;
        title: string;
        kind: "ADMIN_UPLOADED";
        trackScope: TrackScope;
        isActive: true;
        mediaAssetId: string;
        downloadUrl: string;
        mimeType: string;
        sizeBytes: number;
        originalName: string;
      };
      replaced: { materialId: string; mediaAssetId: string | null }[];
      cleanedUpAssets: string[];
    }
  | {
      ok: false;
      code:
        | "LESSON_NOT_FOUND"
        | "LESSON_ARCHIVED"
        | "VALIDATION_FAILED"
        | "INVALID_TRACK_SCOPE";
      message: string;
      validation?: PdfValidationResult;
    };

export type MaterialAccessReason =
  | AccessReason
  | "MATERIAL_NOT_FOUND"
  | "MATERIAL_INACTIVE"
  | "ASSET_NOT_FOUND"
  | "TRACK_DENIED"
  | "FORBIDDEN_ROLE"
  | "UNAUTHORIZED";

export type MaterialAccess =
  | {
      allowed: true;
      reason: null;
      material: {
        id: string;
        lessonId: string;
        title: string;
        trackScope: TrackScope;
        isActive: boolean;
        mediaAssetId: string;
      };
      asset: {
        id: string;
        storageKey: string;
        mimeType: string | null;
        sizeBytes: number | null;
        originalName: string | null;
        isPrivate: boolean;
        storage: string;
        kind: string;
      };
      lesson: {
        id: string;
        status: string;
        trackScope: TrackScope;
        curriculumStatus: string;
        courseId: string | null;
      };
    }
  | { allowed: false; reason: MaterialAccessReason };

// ---------------------------------------------------------------------------
// Legacy pdfUrl helpers
// ---------------------------------------------------------------------------

const PLACEHOLDER_MARKERS = new Set(["", "#", "##", "./#", "null", "none", "-"]);

/** A legacy string url counts only when it is actually a url-ish value. */
export function isUsableLegacyPdfUrl(value: string | null | undefined): boolean {
  if (typeof value !== "string") return false;
  const v = value.trim();
  return v.length > 0 && !PLACEHOLDER_MARKERS.has(v.toLowerCase());
}

/**
 * Build the safe student-facing material list for a lesson.
 *
 * `materials` are already-loaded active Material rows (with optional media).
 * `legacyPdfUrl` is the lesson's `pdfUrl` column — surfaced only as a
 * LEGACY_URL descriptor when no Material of the matching scope is present and
 * the url is usable. Locked callers MUST pass `includeProtected: false` so
 * material ids are never leaked for sessions the student cannot open.
 */
export function buildMaterialDescriptors(input: {
  materials?: readonly {
    id: string;
    title?: string | null;
    kind?: string | null;
    trackScope?: unknown;
    isActive?: boolean | null;
    mediaAssetId?: string | null;
    media?: {
      mimeType?: string | null;
      sizeBytes?: number | null;
    } | null;
  }[] | null;
  legacyPdfUrl?: string | null;
  /** When false, returns an empty list (locked / unpublished redaction). */
  includeProtected?: boolean;
  /** Optional filter: only scopes the viewer is eligible for. */
  eligibleScopes?: Iterable<TrackScope> | null;
}): MaterialDescriptor[] {
  if (input.includeProtected === false) return [];

  const eligible = input.eligibleScopes
    ? new Set(input.eligibleScopes)
    : null;

  const out: MaterialDescriptor[] = [];
  const materials = Array.isArray(input.materials) ? input.materials : [];
  for (const m of materials) {
    if (m?.isActive === false) continue;
    if (!m?.id) continue;
    const scope = normalizeTrackScope(m.trackScope) ?? "SHARED";
    if (eligible && !eligible.has(scope)) continue;
    // A material without a media asset is not downloadable; skip rather than
    // invent a broken descriptor.
    if (!m.mediaAssetId && m.kind !== "GENERATED") {
      // Still surface ADMIN_UPLOADED only when an asset is linked.
      if (m.kind === "ADMIN_UPLOADED" || !m.kind) continue;
    }
    const kind: MaterialDescriptor["kind"] =
      m.kind === "GENERATED" ? "GENERATED" : "ADMIN_UPLOADED";
    out.push({
      id: m.id,
      title: (m.title && String(m.title).trim()) || "Session PDF",
      kind,
      trackScope: scope,
      downloadUrl: m.mediaAssetId ? `/api/materials/${m.id}` : null,
      mimeType: m.media?.mimeType ?? (m.mediaAssetId ? "application/pdf" : null),
      sizeBytes:
        typeof m.media?.sizeBytes === "number" ? m.media.sizeBytes : null,
      legacy: false,
    });
  }

  // Legacy compatibility: only when no Material descriptor exists at all for
  // this payload, and only when the url is a real non-placeholder value.
  // Never invent a material id for a legacy url — the client uses the raw
  // external url, which is the documented compatibility path.
  if (out.length === 0 && isUsableLegacyPdfUrl(input.legacyPdfUrl)) {
    out.push({
      id: "legacy-pdf",
      title: "Session PDF",
      kind: "LEGACY_URL",
      trackScope: "SHARED",
      downloadUrl: String(input.legacyPdfUrl).trim(),
      mimeType: "application/pdf",
      sizeBytes: null,
      legacy: true,
    });
  }

  return out;
}

// ---------------------------------------------------------------------------
// Upload / replace
// ---------------------------------------------------------------------------

/**
 * Parse a trackScope supplied by an admin on upload.
 *   - absent / empty → null (caller inherits the lesson's scope)
 *   - SHARED/ARABIC/LANGUAGE → that scope
 *   - anything else → reject
 */
export function parseMaterialTrackScopeInput(
  raw: unknown
):
  | { ok: true; specified: false }
  | { ok: true; specified: true; value: TrackScope }
  | { ok: false } {
  if (raw === undefined || raw === null) return { ok: true, specified: false };
  if (typeof raw !== "string") return { ok: false };
  const v = raw.trim();
  if (v === "") return { ok: true, specified: false };
  const scope = normalizeTrackScope(v);
  if (!scope) return { ok: false };
  return { ok: true, specified: true, value: scope };
}

/**
 * Upload (or replace) the active PDF material for a lesson × trackScope.
 *
 * Side effects, in order, inside a transaction where possible:
 *   1. Validate bytes (MIME / extension / magic / size).
 *   2. Write private file under an unguessable key.
 *   3. Create MediaAsset(DOCUMENT, LOCAL_PRIVATE, isPrivate).
 *   4. Deactivate prior active Material rows of the same (lesson, trackScope).
 *   5. Create the new Material(ADMIN_UPLOADED) row.
 *   6. Reference-count cleanup of orphaned prior assets (after commit).
 *
 * NEVER writes `Lesson.pdfUrl`. NEVER trusts a client-supplied storageKey.
 */
export async function uploadLessonPdfMaterial(
  input: MaterialUploadInput,
  client: typeof db = db
): Promise<MaterialUploadResult> {
  const lesson = await client.lesson.findUnique({
    where: { id: input.lessonId },
    select: {
      id: true,
      title: true,
      titleAr: true,
      trackScope: true,
      curriculumStatus: true,
      status: true,
    },
  });
  if (!lesson) {
    return {
      ok: false,
      code: "LESSON_NOT_FOUND",
      message: "Lesson not found",
    };
  }
  if (String(lesson.curriculumStatus).toUpperCase() === "ARCHIVED") {
    return {
      ok: false,
      code: "LESSON_ARCHIVED",
      message: "Cannot attach materials to an archived lesson",
    };
  }

  const scopeParse = parseMaterialTrackScopeInput(input.trackScope);
  if (!scopeParse.ok) {
    return {
      ok: false,
      code: "INVALID_TRACK_SCOPE",
      message: "trackScope must be SHARED, ARABIC, or LANGUAGE",
    };
  }
  const trackScope: TrackScope = scopeParse.specified
    ? scopeParse.value
    : normalizeTrackScope(lesson.trackScope) ?? "SHARED";

  const validation = validatePdfUpload({
    buffer: input.buffer,
    claimedMime: input.claimedMime,
    originalName: input.originalName,
    maxBytes: input.maxBytes ?? MAX_PDF_BYTES,
  });
  if (!validation.ok) {
    return {
      ok: false,
      code: "VALIDATION_FAILED",
      message: validation.message,
      validation,
    };
  }

  const storageKey = makeStorageKey("session-pdfs", "pdf");
  const buffer = Buffer.isBuffer(input.buffer)
    ? input.buffer
    : Buffer.from(input.buffer);
  await writePrivateFile(storageKey, buffer);

  const title =
    (typeof input.title === "string" && input.title.trim()) ||
    validation.originalName ||
    `${lesson.title} PDF`;

  // Capture prior active materials so we can deactivate + maybe clean up.
  const prior = await client.material.findMany({
    where: {
      lessonId: lesson.id,
      trackScope,
      isActive: true,
      kind: "ADMIN_UPLOADED",
    },
    select: { id: true, mediaAssetId: true },
  });

  const apply = async (tx: any) => {
    if (prior.length > 0) {
      await tx.material.updateMany({
        where: { id: { in: prior.map((p) => p.id) } },
        data: { isActive: false },
      });
    }

    const asset = await tx.mediaAsset.create({
      data: {
        kind: "DOCUMENT",
        storage: "LOCAL_PRIVATE",
        storageKey,
        mimeType: validation.mimeType,
        sizeBytes: validation.sizeBytes,
        originalName: validation.originalName,
        isPrivate: true,
        createdById: input.actorUserId ?? null,
      },
    });

    const material = await tx.material.create({
      data: {
        lessonId: lesson.id,
        kind: "ADMIN_UPLOADED",
        title: title.slice(0, 200),
        mediaAssetId: asset.id,
        // storageKey on Material is legacy; the asset owns the key. Leave null
        // so nothing ever confuses the two.
        storageKey: null,
        trackScope,
        isActive: true,
      },
    });

    return { asset, material };
  };

  let created: Awaited<ReturnType<typeof apply>>;
  if (typeof (client as { $transaction?: unknown }).$transaction === "function") {
    created = await (client as typeof db).$transaction(apply);
  } else {
    created = await apply(client);
  }

  // Reference-counted cleanup: detach deactivated materials from their prior
  // assets, then delete any asset that nothing else still references. An asset
  // still pointed at by another active Material (or a SessionVideo / evidence
  // row) is retained — never delete shared bytes.
  const cleanedUpAssets = await releaseDetachedAssets(
    prior
      .map((p) => p.mediaAssetId)
      .filter((id): id is string => !!id && id !== created.asset.id),
    client
  );

  return {
    ok: true,
    material: {
      id: created.material.id,
      lessonId: lesson.id,
      title: created.material.title,
      kind: "ADMIN_UPLOADED",
      trackScope,
      isActive: true,
      mediaAssetId: created.asset.id,
      downloadUrl: `/api/materials/${created.material.id}`,
      mimeType: validation.mimeType,
      sizeBytes: validation.sizeBytes,
      originalName: validation.originalName,
    },
    replaced: prior.map((p) => ({
      materialId: p.id,
      mediaAssetId: p.mediaAssetId,
    })),
    cleanedUpAssets,
  };
}

/**
 * Deactivate a material. Bytes are cleaned up only when no other row still
 * references the underlying MediaAsset.
 */
export async function deactivateMaterial(
  materialId: string,
  client: typeof db = db
): Promise<
  | { ok: true; cleanedUpAsset: string | null }
  | { ok: false; code: "MATERIAL_NOT_FOUND"; message: string }
> {
  const material = await client.material.findUnique({
    where: { id: materialId },
    select: { id: true, mediaAssetId: true, isActive: true },
  });
  if (!material) {
    return { ok: false, code: "MATERIAL_NOT_FOUND", message: "Material not found" };
  }

  if (material.isActive) {
    await client.material.update({
      where: { id: materialId },
      data: { isActive: false },
    });
  }

  let cleanedUpAsset: string | null = null;
  if (material.mediaAssetId) {
    const removed = await cleanupUnreferencedMediaAsset(
      material.mediaAssetId,
      client
    );
    if (removed) cleanedUpAsset = material.mediaAssetId;
  }
  return { ok: true, cleanedUpAsset };
}

/**
 * Delete a MediaAsset (and its private bytes) only when NOTHING still
 * references it: no Material, no SessionVideo, no QuizAttemptEvidence.
 * Returns true when the asset was removed.
 */
export async function cleanupUnreferencedMediaAsset(
  mediaAssetId: string,
  client: typeof db = db
): Promise<boolean> {
  const [materialRefs, videoRefs, evidenceRefs, asset] = await Promise.all([
    client.material.count({ where: { mediaAssetId } }),
    client.sessionVideo.count({ where: { mediaAssetId } }),
    client.quizAttemptEvidence.count({ where: { mediaAssetId } }),
    client.mediaAsset.findUnique({
      where: { id: mediaAssetId },
      select: { id: true, storage: true, storageKey: true },
    }),
  ]);

  if (!asset) return false;
  // Active OR inactive materials still count — a deactivated material that
  // keeps its mediaAssetId is a surviving reference (audit / restore path).
  // Callers that want cleanup after deactivate must null the FK first, OR we
  // count only when the material row still points at the asset. The contract
  // is: do not delete bytes while any Material row references them.
  if (materialRefs > 0 || videoRefs > 0 || evidenceRefs > 0) return false;

  if (asset.storage === "LOCAL_PRIVATE" && asset.storageKey) {
    await deletePrivateFile(asset.storageKey);
  }
  await client.mediaAsset.delete({ where: { id: mediaAssetId } }).catch(() => {});
  return true;
}

/**
 * After deactivating a material, optionally release its MediaAsset reference
 * so cleanup can proceed. Used by admin hard-replace when the prior material
 * is not needed for history beyond the AuditLog.
 *
 * Default replace path KEEPS the deactivated Material → MediaAsset link so
 * historical rows remain restorable; cleanup then only fires when the admin
 * explicitly detaches or when no Material remains.
 *
 * For the Phase 14 "stale asset cleanup" path: when a material is deactivated
 * AND no other Material/Video/Evidence references the asset, we still keep the
 * deactivated row's FK (so `materialRefs > 0`). To actually free bytes on
 * replace, the upload path detaches prior materials' mediaAssetId after
 * deactivating them when the caller opts in — see `releaseDetachedAssets`.
 */
export async function releaseDetachedAssets(
  priorMediaAssetIds: (string | null)[],
  client: typeof db = db
): Promise<string[]> {
  const cleaned: string[] = [];
  for (const id of priorMediaAssetIds) {
    if (!id) continue;
    // Detach deactivated materials that still point at this asset so the
    // reference count can drop to zero. Only materials that are already
    // inactive are detached — never an active one.
    await client.material.updateMany({
      where: { mediaAssetId: id, isActive: false },
      data: { mediaAssetId: null },
    });
    const removed = await cleanupUnreferencedMediaAsset(id, client);
    if (removed) cleaned.push(id);
  }
  return cleaned;
}

// ---------------------------------------------------------------------------
// Download authorization (the 10-check contract)
// ---------------------------------------------------------------------------

/**
 * Authorize a download of material `materialId` for the given viewer.
 *
 * Checks (fail closed, in order):
 *   1. authenticated (caller supplies user)
 *   2. role is STUDENT | PARENT | TEACHER | ADMIN
 *   3–8. for STUDENT: canAccessLesson (enrollment, course, track, lifecycle,
 *        progression) + material trackScope eligibility
 *   3–8. for PARENT: isParentLessonPreviewAllowed (child course + child track
 *        + PUBLISHED + not archived) + material trackScope in parent scopes
 *   3–8. for TEACHER/ADMIN: material exists + asset private — staff may review
 *   9. material belongs to its lesson and is active
 *  10. asset exists, is LOCAL_PRIVATE, has a storageKey
 */
export async function authorizeMaterialDownload(params: {
  materialId: string;
  user: { id: string; role: string } | null | undefined;
  client?: typeof db;
}): Promise<MaterialAccess> {
  const client = params.client ?? db;
  const user = params.user;
  if (!user) return { allowed: false, reason: "UNAUTHORIZED" };

  const material = await client.material.findUnique({
    where: { id: params.materialId },
    select: {
      id: true,
      lessonId: true,
      title: true,
      trackScope: true,
      isActive: true,
      mediaAssetId: true,
      kind: true,
      lesson: {
        select: {
          id: true,
          status: true,
          trackScope: true,
          curriculumStatus: true,
          unitId: true,
          topicId: true,
          unit: {
            select: { part: { select: { courseId: true } } },
          },
          topic: {
            select: {
              unit: { select: { part: { select: { courseId: true } } } },
            },
          },
        },
      },
      media: {
        select: {
          id: true,
          storageKey: true,
          mimeType: true,
          sizeBytes: true,
          originalName: true,
          isPrivate: true,
          storage: true,
          kind: true,
        },
      },
    },
  });

  if (!material) return { allowed: false, reason: "MATERIAL_NOT_FOUND" };
  if (!material.isActive) return { allowed: false, reason: "MATERIAL_INACTIVE" };
  if (!material.mediaAssetId || !material.media) {
    return { allowed: false, reason: "ASSET_NOT_FOUND" };
  }
  const asset = material.media;
  if (
    asset.storage !== "LOCAL_PRIVATE" ||
    !asset.storageKey ||
    // Documents must be private; never serve a non-private document asset
    // through this route (defense in depth against a mis-tagged row).
    asset.isPrivate !== true
  ) {
    return { allowed: false, reason: "ASSET_NOT_FOUND" };
  }

  const lesson = material.lesson;
  if (!lesson) return { allowed: false, reason: "MATERIAL_NOT_FOUND" };
  const courseId =
    lesson.unit?.part.courseId ??
    lesson.topic?.unit.part.courseId ??
    null;
  const materialScope = normalizeTrackScope(material.trackScope) ?? "SHARED";
  const lessonScope = normalizeTrackScope(lesson.trackScope) ?? "SHARED";

  const role = String(user.role || "").toUpperCase();

  if (role === "STUDENT") {
    const student = await client.student.findUnique({
      where: { userId: user.id },
      select: { id: true, schoolType: true },
    });
    if (!student) return { allowed: false, reason: "FORBIDDEN_ROLE" };

    // 3–8: full lesson gate (enrollment, course, lesson track, lifecycle,
    // progression). Wrong-track / unpublished / locked → same non-oracle
    // reasons canAccessLesson already uses.
    const access = await canAccessLesson(student.id, lesson.id);
    if (!access.allowed) {
      return {
        allowed: false,
        reason: access.reason ?? "LESSON_NOT_FOUND",
      };
    }

    // Material-level track (may be narrower than the lesson).
    const schoolType =
      normalizeSchoolType(student.schoolType) ??
      (await getStudentSchoolType(student.id));
    if (!canAccessTrackScope(schoolType, materialScope)) {
      return { allowed: false, reason: "TRACK_DENIED" };
    }
  } else if (role === "PARENT") {
    const allowed = await isParentLessonPreviewAllowed(
      user.id,
      {
        status: lesson.status,
        curriculumStatus: lesson.curriculumStatus,
        trackScope: lesson.trackScope,
      },
      courseId
    );
    if (!allowed) return { allowed: false, reason: "MATERIAL_NOT_FOUND" };

    // Parent track set is the UNION of linked enrolled children's tracks.
    // SHARED is always included by getParentTrackScopes; track-specific
    // material requires the matching child track.
    const scopes = await getParentTrackScopes(user.id);
    if (materialScope !== "SHARED" && !scopes.has(materialScope)) {
      return { allowed: false, reason: "TRACK_DENIED" };
    }
  } else if (role === "ADMIN" || role === "TEACHER") {
    // Staff may review any active material. Lifecycle is not a barrier for
    // staging review — that is the point of DRAFT/READY being admin-visible.
  } else {
    return { allowed: false, reason: "FORBIDDEN_ROLE" };
  }

  // Lifecycle note: for students/parents the lesson gate already required
  // PUBLISHED. Staff skip it. We still refuse ARCHIVED for everyone except
  // when staff is reviewing — staff can see archived too (grading history).
  if (
    role !== "ADMIN" &&
    role !== "TEACHER" &&
    (!isStudentVisibleStatus(lesson.status) ||
      String(lesson.curriculumStatus).toUpperCase() === "ARCHIVED")
  ) {
    return { allowed: false, reason: "MATERIAL_NOT_FOUND" };
  }

  return {
    allowed: true,
    reason: null,
    material: {
      id: material.id,
      lessonId: material.lessonId,
      title: material.title,
      trackScope: materialScope,
      isActive: material.isActive,
      mediaAssetId: material.mediaAssetId,
    },
    asset: {
      id: asset.id,
      storageKey: asset.storageKey!,
      mimeType: asset.mimeType,
      sizeBytes: asset.sizeBytes,
      originalName: asset.originalName,
      isPrivate: asset.isPrivate,
      storage: asset.storage,
      kind: asset.kind,
    },
    lesson: {
      id: lesson.id,
      status: String(lesson.status),
      trackScope: lessonScope,
      curriculumStatus: String(lesson.curriculumStatus),
      courseId,
    },
  };
}

/**
 * HTTP status mapping for a material access denial. Mirrors denyProgression
 * semantics so probing material ids cannot enumerate content:
 *   MATERIAL_NOT_FOUND / ASSET_NOT_FOUND / MATERIAL_INACTIVE / TRACK_DENIED
 *     when the lesson itself would 404 → 404
 *   PREVIOUS_SESSION_INCOMPLETE / NOT_ENROLLED → 403 with code
 *   UNAUTHORIZED → 401
 *   FORBIDDEN_ROLE → 403
 */
export function materialAccessHttpStatus(
  reason: MaterialAccessReason
): 401 | 403 | 404 {
  if (reason === "UNAUTHORIZED") return 401;
  if (
    reason === "NOT_ENROLLED" ||
    reason === "PREVIOUS_SESSION_INCOMPLETE" ||
    reason === "FORBIDDEN_ROLE"
  ) {
    return 403;
  }
  // MATERIAL_NOT_FOUND, ASSET_NOT_FOUND, MATERIAL_INACTIVE, TRACK_DENIED,
  // LESSON_NOT_FOUND — never confirm the id is real.
  return 404;
}

/** Content-Disposition helper. */
export function materialContentDisposition(
  filename: string | null | undefined,
  download: boolean
): string {
  const raw = (filename && String(filename).trim()) || "document.pdf";
  // RFC 5987-ish safe token: strip quotes/newlines; keep ASCII filename.
  const safe = raw
    .replace(/["\r\n\\]/g, "")
    .replace(/[^\x20-\x7E]/g, "_")
    .slice(0, 180) || "document.pdf";
  const type = download ? "attachment" : "inline";
  return `${type}; filename="${safe}"`;
}

export { TRACK_SCOPES, MAX_PDF_BYTES };
export type { TrackScope, SchoolType };
