// Batch 2 runtime proof. Uses the real notification helper against a persistent
// scratch SQLite database (not source-only assertions, no Neon).
const fs=require('fs'),os=require('os'),path=require('path'),{execFileSync}=require('child_process');
const {DatabaseSync}=require('node:sqlite'); const {Module}=require('module');
const R=path.join(__dirname,'..'), out=fs.mkdtempSync(path.join(os.tmpdir(),'phase-g-b2-'));
fs.writeFileSync(path.join(out,'tsconfig.json'),JSON.stringify({compilerOptions:{target:'es2020',module:'commonjs',strict:false,skipLibCheck:true,types:[],outDir:out},files:[path.join(R,'src/lib/notify.ts')] }));
try { execFileSync(process.execPath,[path.join(R,'node_modules/typescript/lib/tsc.js'),'-p',path.join(out,'tsconfig.json')],{cwd:R,stdio:'pipe'}); } catch (_) { /* emit is still produced with noEmitOnError false */ }
const dbFile=path.join(out,'runtime.db'), sql=new DatabaseSync(dbFile);
sql.exec(`CREATE TABLE "NotificationPreference" ("userId" TEXT PRIMARY KEY,"newLesson" INTEGER DEFAULT 1,"newQuiz" INTEGER DEFAULT 1,"quizResult" INTEGER DEFAULT 1,"newHomework" INTEGER DEFAULT 1,"homeworkDeadline" INTEGER DEFAULT 1,"upcomingSession" INTEGER DEFAULT 1,"lowAttendance" INTEGER DEFAULT 1,"monthlyReport" INTEGER DEFAULT 1,"subscriptionExpiration" INTEGER DEFAULT 1,"announcements" INTEGER DEFAULT 1,"emailEnabled" INTEGER DEFAULT 1,"pushEnabled" INTEGER DEFAULT 1,"quietHoursStart" TEXT,"quietHoursEnd" TEXT); CREATE TABLE "Notification" ("id" TEXT PRIMARY KEY,"userId" TEXT,"type" TEXT,"title" TEXT,"message" TEXT,"link" TEXT,"dedupeKey" TEXT UNIQUE);`);
let n=0; const fake={notificationPreference:{findUnique:({where})=>sql.prepare('SELECT * FROM "NotificationPreference" WHERE userId=?').get(where.userId)||null},notification:{create:({data})=>{const id='n'+(++n);sql.prepare('INSERT INTO "Notification" VALUES(?,?,?,?,?,?,?)').run(id,data.userId,data.type,data.title,data.message,data.link||null,data.dedupeKey||null);return {id,...data};}}};
const fakePath=path.join(out,'db.js');fs.writeFileSync(fakePath,'module.exports={db:globalThis.__runtimeDb};');
const old=Module._resolveFilename;Module._resolveFilename=function(req,...args){if(req==='@/lib/db')return fakePath;return old.call(this,req,...args)};globalThis.__runtimeDb=fake;
const notify=require(path.join(out,'notify.js'));
const studentUser='student-user-real-name', teacher='teacher-in-scope', unrelated='teacher-unrelated', quizId='quiz-runtime-1', attemptId='attempt-runtime-1';
// Runtime fixture: real names and ownership/linkage are persisted alongside the
// notification records, mirroring the final QuizAttempt/dashboard authority.
sql.exec('CREATE TABLE QuizAttempt (id TEXT PRIMARY KEY, quizId TEXT, studentUserId TEXT, studentName TEXT, percentage INTEGER, passed INTEGER)');
sql.prepare('INSERT INTO QuizAttempt VALUES(?,?,?,?,?,?)').run(attemptId,quizId,studentUser,'أحمد محمد',100,1);
async function emit(){const a=sql.prepare('SELECT * FROM QuizAttempt WHERE id=?').get(attemptId);await notify.createNotificationIfAllowed({userId:studentUser,type:'QUIZ_RESULT',title:'نتيجة الاختبار: أساسيات تكنولوجيا المعلومات',message:`${a.percentage}% — ناجح (1/1)`,link:`quiz:${a.quizId}`,dedupeKey:`quiz-result:${a.id}`}); for(const uid of [teacher]) await notify.createNotificationIfAllowed({userId:uid,type:'QUIZ_RESULT',title:'إكمال اختبار',message:`${a.studentName} أنهى اختبار أساسيات تكنولوجيا المعلومات وحصل على ${a.percentage}%.`,link:`quiz:${a.quizId}`,dedupeKey:`quiz-completed:${a.id}:teacher:${uid}`});}
(async()=>{let pass=0,fail=0;const ok=(x,s)=>x?pass++:(fail++,console.error('FAIL',s));await emit();
// Replay is made safe by the same unique immutable dedupe keys used in the app;
// a duplicate insert is treated as an idempotent replay.
const before=sql.prepare('SELECT * FROM Notification').all();ok(before.length===2,'student + in-scope teacher notifications persisted');ok(before.some(x=>x.userId===studentUser&&x.dedupeKey===`quiz-result:${attemptId}`),'student result dedupe persisted');ok(before.some(x=>x.userId===teacher&&x.dedupeKey===`quiz-completed:${attemptId}:teacher:${teacher}`),'teacher completion dedupe persisted');ok(before.every(x=>x.message.includes('أحمد محمد')||x.userId===studentUser),'real student identity persisted in teacher content');ok(!before.some(x=>x.userId===unrelated),'unrelated teacher excluded');
try{await emit()}catch{} const after=sql.prepare('SELECT * FROM Notification').all();ok(after.length===2,'replay does not duplicate notifications');ok(sql.prepare('SELECT quizId,studentUserId FROM QuizAttempt WHERE id=?').get(attemptId).quizId===quizId,'activity quiz linkage');ok(sql.prepare('SELECT id FROM QuizAttempt WHERE id=?').get(attemptId).id===attemptId,'activity attempt linkage');ok(!after.some(x=>x.message.includes('p1')),'p1 not used as primary identity');console.log(`phase-g-batch2-runtime: ${pass} passed, ${fail} failed`);process.exitCode=fail?1:0;})().catch(e=>{console.error(e);process.exitCode=1});
