#!/usr/bin/env node
// Emits src/lib/i18n-dict.ts from the merge report (key -> {ar, en}).
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const here = path.dirname(fileURLToPath(import.meta.url));
const { mapping } = JSON.parse(fs.readFileSync(path.join(here, "merge-report.json"), "utf8"));
const norm = (s) => s.replace(/\s+/g, " ").trim();

const dict = {};
for (const e of mapping) {
  const ar = e.kind === "tmpl" ? e.shape || e.ar : norm(e.ar);
  if (!dict[e.key]) dict[e.key] = { ar, en: e.en };
  else if (dict[e.key].ar !== ar) {
    // same key (file+text collision) — keep first; dedupe by content check
    if (dict[e.key].en !== e.en) {
      console.error("KEY COLLISION", e.key, JSON.stringify(ar), "vs", JSON.stringify(dict[e.key].ar));
    }
  }
}

const keys = Object.keys(dict).sort();
const lines = [];
lines.push("// AUTO-GENERATED by scripts/i18n/emit-dict.mjs — do not edit by hand.");
lines.push("// Source: scripts/i18n/catalog.json + scripts/i18n/en/ar2en.*.mjs");
lines.push("// Regenerate: node scripts/i18n/extract-catalog.mjs && node scripts/i18n/merge-catalog.mjs && node scripts/i18n/emit-dict.mjs");
lines.push("");
lines.push('export type DictEntry = { ar: string; en: string };');
lines.push("");
lines.push("export const DICT: Record<string, DictEntry> = {");
for (const k of keys) {
  const { ar, en } = dict[k];
  const q = (s) => JSON.stringify(s);
  lines.push(`  ${q(k)}: { ar: ${q(ar)}, en: ${q(en)} },`);
}
lines.push("};");
lines.push("");

fs.mkdirSync("src/lib", { recursive: true });
fs.writeFileSync("src/lib/i18n-dict.ts", lines.join("\n"));
console.log("emitted src/lib/i18n-dict.ts with", keys.length, "entries");
